/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as ProfesionalesRouteImport } from './routes/profesionales'
import { Route as RecuperarRouteImport } from './routes/recuperar'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedMiCuentaRouteImport } from './routes/_authenticated/mi-cuenta'
import { Route as AuthenticatedReservarRouteImport } from './routes/_authenticated/reservar'
import { Route as ServiciosIndexRouteImport } from './routes/servicios.index'
import { Route as ServiciosServiceIdRouteImport } from './routes/servicios.$serviceId'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminCategoriasProductosRouteImport } from './routes/_authenticated/admin.categorias-productos'
import { Route as AuthenticatedAdminCategoriasServiciosRouteImport } from './routes/_authenticated/admin.categorias-servicios'
import { Route as AuthenticatedAdminClientesRouteImport } from './routes/_authenticated/admin.clientes'
import { Route as AuthenticatedAdminCuentaRouteImport } from './routes/_authenticated/admin.cuenta'
import { Route as AuthenticatedAdminEquipoRouteImport } from './routes/_authenticated/admin.equipo'
import { Route as AuthenticatedAdminMiAgendaRouteImport } from './routes/_authenticated/admin.mi-agenda'
import { Route as AuthenticatedAdminProductosRouteImport } from './routes/_authenticated/admin.productos'
import { Route as AuthenticatedAdminProfesionalesRouteImport } from './routes/_authenticated/admin.profesionales'
import { Route as AuthenticatedAdminServiciosRouteImport } from './routes/_authenticated/admin.servicios'
import { Route as AuthenticatedAdminTurnosRouteImport } from './routes/_authenticated/admin.turnos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfesionalesRoute = ProfesionalesRouteImport.update({
  id: '/profesionales',
  path: '/profesionales',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarRoute = RecuperarRouteImport.update({
  id: '/recuperar',
  path: '/recuperar',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMiCuentaRoute = AuthenticatedMiCuentaRouteImport.update({
  id: '/mi-cuenta',
  path: '/mi-cuenta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReservarRoute = AuthenticatedReservarRouteImport.update({
  id: '/reservar',
  path: '/reservar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ServiciosIndexRoute = ServiciosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServiciosRoute,
} as any)
const ServiciosServiceIdRoute = ServiciosServiceIdRouteImport.update({
  id: '/$serviceId',
  path: '/$serviceId',
  getParentRoute: () => ServiciosRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCategoriasProductosRoute =
  AuthenticatedAdminCategoriasProductosRouteImport.update({
    id: '/categorias-productos',
    path: '/categorias-productos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoriasServiciosRoute =
  AuthenticatedAdminCategoriasServiciosRouteImport.update({
    id: '/categorias-servicios',
    path: '/categorias-servicios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClientesRoute =
  AuthenticatedAdminClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCuentaRoute =
  AuthenticatedAdminCuentaRouteImport.update({
    id: '/cuenta',
    path: '/cuenta',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEquipoRoute =
  AuthenticatedAdminEquipoRouteImport.update({
    id: '/equipo',
    path: '/equipo',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMiAgendaRoute =
  AuthenticatedAdminMiAgendaRouteImport.update({
    id: '/mi-agenda',
    path: '/mi-agenda',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductosRoute =
  AuthenticatedAdminProductosRouteImport.update({
    id: '/productos',
    path: '/productos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProfesionalesRoute =
  AuthenticatedAdminProfesionalesRouteImport.update({
    id: '/profesionales',
    path: '/profesionales',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminServiciosRoute =
  AuthenticatedAdminServiciosRouteImport.update({
    id: '/servicios',
    path: '/servicios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTurnosRoute =
  AuthenticatedAdminTurnosRouteImport.update({
    id: '/turnos',
    path: '/turnos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contacto': typeof ContactoRoute
  '/profesionales': typeof ProfesionalesRoute
  '/recuperar': typeof RecuperarRoute
  '/servicios': typeof ServiciosRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/mi-cuenta': typeof AuthenticatedMiCuentaRoute
  '/reservar': typeof AuthenticatedReservarRoute
  '/servicios/$serviceId': typeof ServiciosServiceIdRoute
  '/servicios/': typeof ServiciosIndexRoute
  '/admin/categorias-productos': typeof AuthenticatedAdminCategoriasProductosRoute
  '/admin/categorias-servicios': typeof AuthenticatedAdminCategoriasServiciosRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/cuenta': typeof AuthenticatedAdminCuentaRoute
  '/admin/equipo': typeof AuthenticatedAdminEquipoRoute
  '/admin/mi-agenda': typeof AuthenticatedAdminMiAgendaRoute
  '/admin/productos': typeof AuthenticatedAdminProductosRoute
  '/admin/profesionales': typeof AuthenticatedAdminProfesionalesRoute
  '/admin/servicios': typeof AuthenticatedAdminServiciosRoute
  '/admin/turnos': typeof AuthenticatedAdminTurnosRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contacto': typeof ContactoRoute
  '/profesionales': typeof ProfesionalesRoute
  '/recuperar': typeof RecuperarRoute
  '/mi-cuenta': typeof AuthenticatedMiCuentaRoute
  '/reservar': typeof AuthenticatedReservarRoute
  '/servicios/$serviceId': typeof ServiciosServiceIdRoute
  '/servicios': typeof ServiciosIndexRoute
  '/admin/categorias-productos': typeof AuthenticatedAdminCategoriasProductosRoute
  '/admin/categorias-servicios': typeof AuthenticatedAdminCategoriasServiciosRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/cuenta': typeof AuthenticatedAdminCuentaRoute
  '/admin/equipo': typeof AuthenticatedAdminEquipoRoute
  '/admin/mi-agenda': typeof AuthenticatedAdminMiAgendaRoute
  '/admin/productos': typeof AuthenticatedAdminProductosRoute
  '/admin/profesionales': typeof AuthenticatedAdminProfesionalesRoute
  '/admin/servicios': typeof AuthenticatedAdminServiciosRoute
  '/admin/turnos': typeof AuthenticatedAdminTurnosRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contacto': typeof ContactoRoute
  '/profesionales': typeof ProfesionalesRoute
  '/recuperar': typeof RecuperarRoute
  '/servicios': typeof ServiciosRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/mi-cuenta': typeof AuthenticatedMiCuentaRoute
  '/_authenticated/reservar': typeof AuthenticatedReservarRoute
  '/servicios/$serviceId': typeof ServiciosServiceIdRoute
  '/servicios/': typeof ServiciosIndexRoute
  '/_authenticated/admin/categorias-productos': typeof AuthenticatedAdminCategoriasProductosRoute
  '/_authenticated/admin/categorias-servicios': typeof AuthenticatedAdminCategoriasServiciosRoute
  '/_authenticated/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/_authenticated/admin/cuenta': typeof AuthenticatedAdminCuentaRoute
  '/_authenticated/admin/equipo': typeof AuthenticatedAdminEquipoRoute
  '/_authenticated/admin/mi-agenda': typeof AuthenticatedAdminMiAgendaRoute
  '/_authenticated/admin/productos': typeof AuthenticatedAdminProductosRoute
  '/_authenticated/admin/profesionales': typeof AuthenticatedAdminProfesionalesRoute
  '/_authenticated/admin/servicios': typeof AuthenticatedAdminServiciosRoute
  '/_authenticated/admin/turnos': typeof AuthenticatedAdminTurnosRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contacto'
    | '/profesionales'
    | '/recuperar'
    | '/servicios'
    | '/admin'
    | '/mi-cuenta'
    | '/reservar'
    | '/servicios/$serviceId'
    | '/servicios/'
    | '/admin/categorias-productos'
    | '/admin/categorias-servicios'
    | '/admin/clientes'
    | '/admin/cuenta'
    | '/admin/equipo'
    | '/admin/mi-agenda'
    | '/admin/productos'
    | '/admin/profesionales'
    | '/admin/servicios'
    | '/admin/turnos'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contacto'
    | '/profesionales'
    | '/recuperar'
    | '/mi-cuenta'
    | '/reservar'
    | '/servicios/$serviceId'
    | '/servicios'
    | '/admin/categorias-productos'
    | '/admin/categorias-servicios'
    | '/admin/clientes'
    | '/admin/cuenta'
    | '/admin/equipo'
    | '/admin/mi-agenda'
    | '/admin/productos'
    | '/admin/profesionales'
    | '/admin/servicios'
    | '/admin/turnos'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contacto'
    | '/profesionales'
    | '/recuperar'
    | '/servicios'
    | '/_authenticated/admin'
    | '/_authenticated/mi-cuenta'
    | '/_authenticated/reservar'
    | '/servicios/$serviceId'
    | '/servicios/'
    | '/_authenticated/admin/categorias-productos'
    | '/_authenticated/admin/categorias-servicios'
    | '/_authenticated/admin/clientes'
    | '/_authenticated/admin/cuenta'
    | '/_authenticated/admin/equipo'
    | '/_authenticated/admin/mi-agenda'
    | '/_authenticated/admin/productos'
    | '/_authenticated/admin/profesionales'
    | '/_authenticated/admin/servicios'
    | '/_authenticated/admin/turnos'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactoRoute: typeof ContactoRoute
  ProfesionalesRoute: typeof ProfesionalesRoute
  RecuperarRoute: typeof RecuperarRoute
  ServiciosRoute: typeof ServiciosRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profesionales': {
      id: '/profesionales'
      path: '/profesionales'
      fullPath: '/profesionales'
      preLoaderRoute: typeof ProfesionalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar': {
      id: '/recuperar'
      path: '/recuperar'
      fullPath: '/recuperar'
      preLoaderRoute: typeof RecuperarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mi-cuenta': {
      id: '/_authenticated/mi-cuenta'
      path: '/mi-cuenta'
      fullPath: '/mi-cuenta'
      preLoaderRoute: typeof AuthenticatedMiCuentaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reservar': {
      id: '/_authenticated/reservar'
      path: '/reservar'
      fullPath: '/reservar'
      preLoaderRoute: typeof AuthenticatedReservarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/servicios/': {
      id: '/servicios/'
      path: '/'
      fullPath: '/servicios/'
      preLoaderRoute: typeof ServiciosIndexRouteImport
      parentRoute: typeof ServiciosRoute
    }
    '/servicios/$serviceId': {
      id: '/servicios/$serviceId'
      path: '/$serviceId'
      fullPath: '/servicios/$serviceId'
      preLoaderRoute: typeof ServiciosServiceIdRouteImport
      parentRoute: typeof ServiciosRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categorias-productos': {
      id: '/_authenticated/admin/categorias-productos'
      path: '/categorias-productos'
      fullPath: '/admin/categorias-productos'
      preLoaderRoute: typeof AuthenticatedAdminCategoriasProductosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categorias-servicios': {
      id: '/_authenticated/admin/categorias-servicios'
      path: '/categorias-servicios'
      fullPath: '/admin/categorias-servicios'
      preLoaderRoute: typeof AuthenticatedAdminCategoriasServiciosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clientes': {
      id: '/_authenticated/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AuthenticatedAdminClientesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cuenta': {
      id: '/_authenticated/admin/cuenta'
      path: '/cuenta'
      fullPath: '/admin/cuenta'
      preLoaderRoute: typeof AuthenticatedAdminCuentaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/equipo': {
      id: '/_authenticated/admin/equipo'
      path: '/equipo'
      fullPath: '/admin/equipo'
      preLoaderRoute: typeof AuthenticatedAdminEquipoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/mi-agenda': {
      id: '/_authenticated/admin/mi-agenda'
      path: '/mi-agenda'
      fullPath: '/admin/mi-agenda'
      preLoaderRoute: typeof AuthenticatedAdminMiAgendaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/productos': {
      id: '/_authenticated/admin/productos'
      path: '/productos'
      fullPath: '/admin/productos'
      preLoaderRoute: typeof AuthenticatedAdminProductosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/profesionales': {
      id: '/_authenticated/admin/profesionales'
      path: '/profesionales'
      fullPath: '/admin/profesionales'
      preLoaderRoute: typeof AuthenticatedAdminProfesionalesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/servicios': {
      id: '/_authenticated/admin/servicios'
      path: '/servicios'
      fullPath: '/admin/servicios'
      preLoaderRoute: typeof AuthenticatedAdminServiciosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/turnos': {
      id: '/_authenticated/admin/turnos'
      path: '/turnos'
      fullPath: '/admin/turnos'
      preLoaderRoute: typeof AuthenticatedAdminTurnosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCategoriasProductosRoute: typeof AuthenticatedAdminCategoriasProductosRoute
  AuthenticatedAdminCategoriasServiciosRoute: typeof AuthenticatedAdminCategoriasServiciosRoute
  AuthenticatedAdminClientesRoute: typeof AuthenticatedAdminClientesRoute
  AuthenticatedAdminCuentaRoute: typeof AuthenticatedAdminCuentaRoute
  AuthenticatedAdminEquipoRoute: typeof AuthenticatedAdminEquipoRoute
  AuthenticatedAdminMiAgendaRoute: typeof AuthenticatedAdminMiAgendaRoute
  AuthenticatedAdminProductosRoute: typeof AuthenticatedAdminProductosRoute
  AuthenticatedAdminProfesionalesRoute: typeof AuthenticatedAdminProfesionalesRoute
  AuthenticatedAdminServiciosRoute: typeof AuthenticatedAdminServiciosRoute
  AuthenticatedAdminTurnosRoute: typeof AuthenticatedAdminTurnosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCategoriasProductosRoute:
    AuthenticatedAdminCategoriasProductosRoute,
  AuthenticatedAdminCategoriasServiciosRoute:
    AuthenticatedAdminCategoriasServiciosRoute,
  AuthenticatedAdminClientesRoute: AuthenticatedAdminClientesRoute,
  AuthenticatedAdminCuentaRoute: AuthenticatedAdminCuentaRoute,
  AuthenticatedAdminEquipoRoute: AuthenticatedAdminEquipoRoute,
  AuthenticatedAdminMiAgendaRoute: AuthenticatedAdminMiAgendaRoute,
  AuthenticatedAdminProductosRoute: AuthenticatedAdminProductosRoute,
  AuthenticatedAdminProfesionalesRoute: AuthenticatedAdminProfesionalesRoute,
  AuthenticatedAdminServiciosRoute: AuthenticatedAdminServiciosRoute,
  AuthenticatedAdminTurnosRoute: AuthenticatedAdminTurnosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedMiCuentaRoute: typeof AuthenticatedMiCuentaRoute
  AuthenticatedReservarRoute: typeof AuthenticatedReservarRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedMiCuentaRoute: AuthenticatedMiCuentaRoute,
  AuthenticatedReservarRoute: AuthenticatedReservarRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ServiciosRouteChildren {
  ServiciosServiceIdRoute: typeof ServiciosServiceIdRoute
  ServiciosIndexRoute: typeof ServiciosIndexRoute
}

const ServiciosRouteChildren: ServiciosRouteChildren = {
  ServiciosServiceIdRoute: ServiciosServiceIdRoute,
  ServiciosIndexRoute: ServiciosIndexRoute,
}

const ServiciosRouteWithChildren = ServiciosRoute._addFileChildren(
  ServiciosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactoRoute: ContactoRoute,
  ProfesionalesRoute: ProfesionalesRoute,
  RecuperarRoute: RecuperarRoute,
  ServiciosRoute: ServiciosRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
